so ~/.vim/config/plug.vim
so ~/.vim/config/preferences.vim
so ~/.vim/config/keymaps.vim
so ~/.vim/config/lsp.vim
so ~/.vim/config/treesitter.vim
so ~/.vim/config/extraPlugings.vim
" DAP
" cpp
so ~/.vim/config/dap/cpp.vim
" setup
so ~/.vim/config/dap/general.vim
so ~/.vim/config/theme.vim
so ~/.vim/config/nerdtree.vim
