vim.cmd([[packadd packer.nvim]])
return require("packer").startup(function()
	use("wbthomason/packer.nvim")
	use("kyazdani42/nvim-web-devicons")
	use("christoomey/vim-tmux-navigator")
	use("neovim/nvim-lspconfig")
	use("williamboman/nvim-lsp-installer")
	use("b0o/schemastore.nvim")
	use("hrsh7th/nvim-cmp")
	use("hrsh7th/cmp-nvim-lsp")
	use("saadparwaiz1/cmp_luasnip")
	use("L3MON4D3/LuaSnip")
	use("rafamadriz/friendly-snippets")
	use({ "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" })
	use("jiangmiao/auto-pairs")
	use("nvim-lua/plenary.nvim")
	use("nvim-telescope/telescope.nvim")
	use({ "nvim-telescope/telescope-fzf-native.nvim", run = "make" })
	use("liuchengxu/vista.vim")
	use("terryma/vim-multiple-cursors")
	use("mfussenegger/nvim-jdtls")
	use("lervag/vimtex")
	use("ray-x/lsp_signature.nvim")
	use("jose-elias-alvarez/nvim-lsp-ts-utils")
	use("folke/lsp-colors.nvim")
	use("folke/twilight.nvim")
	use("folke/trouble.nvim")
	use("jose-elias-alvarez/null-ls.nvim")
        use {
            'numToStr/Comment.nvim',
            config = function()
                require('Comment').setup()
            end
        }
	use("JoosepAlviste/nvim-ts-context-commentstring")
	use("windwp/nvim-ts-autotag")
	use("tell-k/vim-autopep8")
	use("norcalli/nvim-colorizer.lua")
	use("hoob3rt/lualine.nvim")
	use("hrsh7th/cmp-emoji")
	use("hrsh7th/cmp-calc")
	use("hrsh7th/cmp-path")
	use("hrsh7th/cmp-buffer")
	use("onsails/lspkind-nvim")
	-- use("mhinz/vim-signify")
	use("fladson/vim-kitty")
	use("mfussenegger/nvim-dap")
	use("rcarriga/nvim-dap-ui")
	use("theHamsta/nvim-dap-virtual-text")
	use("nvim-treesitter/playground")
	use("wakatime/vim-wakatime")
	use("Pocco81/DAPInstall.nvim")
	use("rmagatti/auto-session")
	use("kyazdani42/nvim-tree.lua")
	use("catppuccin/nvim")
	use("p00f/nvim-ts-rainbow")
	use({ "iamcco/markdown-preview.nvim", run = "cd app && yarn install" })
	use("morphisjustfun/nvim-code2text")
	use("folke/tokyonight.nvim")
	use("github/copilot.vim")
	use("akinsho/flutter-tools.nvim")
	use("rktjmp/lush.nvim")
	use("kristijanhusak/vim-carbon-now-sh")
	use("rcarriga/nvim-notify")
        use("weilbith/nvim-code-action-menu")
end)
